auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_auction", views.create_auction, name='create_auction'),
    path("auction/<int:auction_id>", views.auction_page, name='auction'),
    path("toggle_watchlist/<int:auction_id>", views.toggle_watchlist, name='toggle_watchlist'),
    path("bid/<int:auction_id>", views.bid, name='bid'),
    path("close/<int:auction_id>", views.close_auction, name='close'),
    path("add_comment/<int:auction_id>", views.add_comment, name='add_comment'),
    path("watchlist", views.watchlist, name='watchlist'),
    path("categories", views.categories, name='categories'),
    path("category/<str:category>", views.category, name='category')
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models


class User(AbstractUser):

    watchlist = models.ManyToManyField('Auction', blank=True)

    def __str__(self):
        return f'{self.username}'

class Auction(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    creationDate = models.DateField(auto_now_add=True)
    image = models.URLField(blank=True)

    FASHION = 'FA'
    TOYS = 'TO'
    ELECTRONICS = 'EL'
    HOME = 'HO'
    CATEGORY_CHOISES = [
        (FASHION, 'Fashion'),
        (TOYS, 'Toys'),
        (ELECTRONICS, 'Electronics'),
        (HOME, 'Home')]
    category = models.CharField(max_length=2, choices=CATEGORY_CHOISES, blank=True)
    
    #When a new bid to the auction is created, the price is updated
    price = models.PositiveIntegerField(help_text='Not to exceed 2147483647!')
    def set_price(self, price):
        self.price = price
        self.save()

    is_active = models.BooleanField(default=True)
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_auctions")

    def close(self):
        # This query coulb be avoided by adding a 'last_bidder' attribe to the Auction model
        # And implementig a method 'Auction.set_price_and_bidder(amount=self.amount, last_bidder=self.user) inside the bid clean() method
        # If this were a real Auction site with millions of bids per second,
        # then it would be sensible to implement the auction closing in the beforementioned way
        # But I want to familiarize miself with the Django queries so I implement it this way

        # .objects brings me the Bid manager
        # .all() brings me the full table
        # .filter(auction=self) is equivalent to WHERE id = ...
        # .order_by('amount') is selfexplanatory
        # the 'minus' (-) in '-amount' tells the order_by method to sort by descending order
        # [0] gets the first element
        try:
            winner = Bid.objects.all().filter(auction=self).order_by('-amount')[0].user
        except IndexError:
            winner = None
        # The latter query fails when there's no bid. Fix that

        if winner is not None: self.winner=winner

        self.set_active_status(False)
        self.save()

    def set_active_status(self,status):
        self.is_active = status
        self.save()

    # When updating winner, the following constrain is applied: 
    # if winner is not null: is_active = False        
    def clean(self):
        if self.winner is not None:
            self.set_active_status(False)
            
    def __str__(self):
        return f'{self.title} {self.creationDate} {self.price}$ A:{self.is_active} W:{self.winner} C:{self.creator}'

class Comment(models.Model):
    content = models.TextField()
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)

    def __str__(self):
        content_len = len(self.content)
        preview_thresshold = 12
        if content_len >= preview_thresshold:
            content_preview = self.content[0:preview_thresshold] + '...'
        else:
            content_preview = self.content
        return f'{self.user}: -> {self.auction.title}: {content_preview}'

class Bid(models.Model):
    
    amount = models.PositiveIntegerField()
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='bids')

    def __str__(self):
        return f'{self.user} bids {self.amount} to {self.auction.title}'

    def clean(self):
        # When creating a Bid, the following constrains are implemented:
        if self.amount <= self.auction.price:
            raise ValidationError(f'Amount should be greater than {self.auction.price}')
        else:
            self.auction.set_price(self.amount)
        # Do not create bids on closed auctions
        if not self.auction.is_active:
            raise ValidationError(f'Cannot create bids on closed auctions')

auctions/forms.py
from django.forms import ModelForm
from .models import Auction, Comment

class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        exclude = ['creator','is_active','winner']

# There is no a Form for Bid because I wanted to set the min_value
# of the 'amount' field corresponding to the 'amount' attribute of the Auction Model
# every time I created a new BidForm,
# but I couldn't find a way to do it with the Django ModelForm class,
# So I did it manually

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['date','user','auction']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import AuctionForm, CommentForm
from .models import Auction, Bid, Comment, User


def get_auction_number(request):
    try:
        auctions_in_watchlist = request.user.watchlist.all().count()
    except:
        auctions_in_watchlist = 0
    return auctions_in_watchlist

def index(request):
    return render(request, "auctions/index.html", {
        'auctions': Auction.objects.exclude(is_active=False).all(),
        'auctions_in_watchlist': get_auction_number(request)
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='login')
def create_auction(request):

    if (request.method == 'POST'):
        
        auction_form = AuctionForm(request.POST)
        
        if auction_form.is_valid():
            auction_form.instance.creator = request.user
            auction_form.save()
            return HttpResponseRedirect(reverse(index))

        return render(request, "auctions/create_auction.html", {
            'form': auction_form,
            'message': 'Invalid form',
            'auctions_in_watchlist': get_auction_number(request)
        })

    else:
        form = AuctionForm()
        return render(request, "auctions/create_auction.html", {
            'form': form,
            'auctions_in_watchlist': get_auction_number(request)
        })


def auction_page(request,auction_id):
    #Ensure the requested auction exists
    try:
        auction = Auction.objects.get(id=auction_id)    
    except ObjectDoesNotExist:
        return render(request, "auctions/auction_page.html", {
            'message': 'There was a problem getting the requested auction',
            'auctions_in_watchlist': get_auction_number(request)
        })

    #Ensure the user is logged In
    try:
        auction_in_watchlist = auction in request.user.watchlist.all()
        
    except AttributeError:
        return render(request, "auctions/auction_page.html", {
            'auction': auction
        }) 

    #Define watchlist button message
    if auction_in_watchlist: watchlist_message = 'Remove from Watchlist'
    else: watchlist_message = 'Add to Watchlist'
    
    # Define minimun bid value
    min_bid_value = auction.price + 1

    # Define if the user is the one who created the listing
    # Any of the two following works
    user_is_creator = auction.creator == request.user
    user_is_creator = auction in request.user.created_auctions.all()

    #Define if the user is the winner
    user_is_winner = auction.winner == request.user

    # Get the comments
    comments = Comment.objects.all().filter(auction=auction_id)

    # Define a comment form
    comment_form = CommentForm()

    # Define number of bids already made of the auction
    # number_of_bids = Bid.objects.filter(auction=auction).count()
    number_of_bids = auction.bids.count()

    # Define if your bid is the current bid
    try: user_is_last_bidder = request.user == auction.bids.all().order_by('-amount')[0].user
    except: user_is_last_bidder = False

    return render(request, "auctions/auction_page.html", {
        'auction': auction,
        'watchlist_message': watchlist_message,
        'min_bid_value': min_bid_value,
        'user_is_creator': user_is_creator,
        'user_is_winner': user_is_winner,
        'comment_form': comment_form,
        'comments': comments,
        'auctions_in_watchlist': get_auction_number(request),
        'number_of_bids': number_of_bids,
        'user_is_last_bidder': user_is_last_bidder
    })

@login_required(login_url='login')
def toggle_watchlist(request, auction_id):

    try:
        auction = Auction.objects.get(id=auction_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

    watchlist = request.user.watchlist.all()

    if auction in watchlist :
        request.user.watchlist.remove(auction)
    else:
        request.user.watchlist.add(auction)

    return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

@login_required(login_url='login')
def bid(request, auction_id):

    if request.method == 'POST':
        
        # Ensure User has not changed the amount input name
        try:
            amount = int(request.POST['amount'])
        except:
            #Implement something better, like redirecting to auction_page
            # with an error message on the bid form
            return render(request, "auctions/auction_page.html", {
                'message': 'Error in bid amount Field',
                'auctions_in_watchlist': get_auction_number(request)
            })

        user = request.user

        try:
            auction = Auction.objects.get(id=auction_id)
        except ObjectDoesNotExist:
            return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

        bid = Bid(amount=amount,user=user,auction=auction)
        try:
            bid.clean()
        except ValidationError:
            # Error should be presented in auction url.
            # Error message should be on the bid input itself
            return render(request, "auctions/auction_page.html", {
                'message': 'Error in bid amount',
                'auctions_in_watchlist': get_auction_number(request)
            })
        bid.save()

    return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

@login_required(login_url='login')
def close_auction(request, auction_id):

    #Ensure the requested auction exists
    try:
        auction = Auction.objects.get(id=auction_id)    
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

    auction.close()
    return HttpResponseRedirect(reverse("auction", args=(auction_id,)))


@login_required(login_url='login')
def add_comment(request, auction_id):

    if request.method == 'POST':

        # Make sure the auction exist
        try:
            auction = Auction.objects.get(id=auction_id)
        except ObjectDoesNotExist:
            return HttpResponseRedirect(reverse("auction", args=(auction_id,)))

        comment_form = CommentForm(request.POST)

        user = request.user

        if comment_form.is_valid():
            comment_form.instance.user = user
            comment_form.instance.auction = auction
            comment_form.save()
        else:
            # This message should be pressented in the Auction Page, wiht the auction url
            return HttpResponse('Ivalid comment')
    return HttpResponseRedirect(reverse("auction", args=(auction_id,)))


@login_required(login_url='login')
def watchlist(request):
    watchlist = request.user.watchlist.all()
    return render(request, "auctions/index.html", {
        'auctions': watchlist,
        'watchlist_view': True,
        'auctions_in_watchlist': watchlist.count()
    })

def categories(request):
    categories = Auction.CATEGORY_CHOISES
    return render(request, "auctions/categories.html", {
        'categories': categories,
        'auctions_in_watchlist': get_auction_number(request)
    })


def category(request, category):

    auctions = Auction.objects.all().filter(category=category).filter(is_active=True)

    category_h = ''
    for cat in Auction.CATEGORY_CHOISES:
        if cat[0] == category: category_h = cat[1]
        
    return render(request, "auctions/index.html", {
        'category_human_readable': category_h,
        'auctions': auctions,
        'auctions_in_watchlist': get_auction_number(request)
    })

auctions/templates/auctions/auction_page.html
{% extends "auctions/layout.html" %}

{% block body%}

    {% if message %}
        <div>{{ message }}</div>
    {% else %}

        {% if user.is_authenticated %}
            <form action="{% url 'toggle_watchlist' auction.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="{{ watchlist_message }}">
            </form>
        {% else %}
        {% endif %}
        
        <div class="card">
            <img class="card-img-top rounded" src="{{ auction.image }}" alt="This auction has no image" style="max-width: 50%;">
            <div class="card-body">
                <h1 class="card-title">Title: {{ auction.title }}</h1>
                <p class="card-text">Description: {{ auction.description }}</p>
                <p class="card-text"><b>Price: ${{ auction.price }}</b></p>
            </div>
        </div>
        
        {% if user.is_authenticated %}

            {% if auction.is_active %}

                {% if user_is_creator %}

                    <div class="card">
                        <div class="card-body">
                            <form action="{% url 'close' auction.id %}" method="POST">
                                {% csrf_token %}
                                <p class="card-text" for="id_close">Close auction</p>
                                <input class="btn btn-warning" id="id_close" type="submit" value="Close">
                            </form>
                        </div>
                    </div>

                {% else %}

                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">
                                ({{ number_of_bids }}) bids so far.
                                {% if user_is_last_bidder %}
                                Your bid is the current bid.
                                {% endif %}
                            </p>
                            <p class="card-text">Bid on the Auction!</p>
                            <form action="{% url 'bid' auction.id %}" method="POST">
                                {% csrf_token %}
                                <label for="id_amount">Amount:</label>
                                <input id="id_amount" type="number" name="amount" min="{{ min_bid_value }}" required="">
                                <input type="submit" value="Bid!" class="btn btn-success">
                            </form>        
                        </div>
                    </div>

                {% endif %}
            
            {% elif user_is_winner %}
                <div class="alert alert-success" role="alert">
                    <h1>You're the winner!</h1>
                </div>
            {% else %}
            {% endif %}
        {% endif %}
        
        <div>
            <h3>Details</h3>
            <ul>
                <li>Listed by: {{ auction.creator }}</li>
                <li>Category: 
                    {% if auction.get_category_display %}
                        {{auction.get_category_display}}
                    {% else %}
                        No category Listed
                    {% endif %}
                </li>
            </ul>
        </div>

        <div>
            <h1>Comments</h1>

            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Add comment</h3>    
                    <form action="{% url 'add_comment' auction.id %}" method="POST">
                        {% csrf_token %}
                        {{ comment_form }}
                        <br>
                        <input type="submit" value="Add comment" class="btn btn-primary">
                    </form>
                </div>
            </div>

            <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <b>{{ comment.user }}: </b>
                    {{ comment.content }}
                </li>
            {% endfor %}
            </ul>
        </div>

    {% endif %}

{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h1>Categories</h1>
    
    {% for category in categories %}
        <ul>
            <li>
                <a href="{% url 'category' category.0 %}">{{ category.1 }}</a>
            </li>
        </ul>
    {% endfor %}
    
{% endblock %}

auctions/templates/auctions/create_auction.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
<form action="{% url 'create_auction' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% if watchlist_view %}
        <h2>Auctions in watchlist</h2>
    {% elif category_human_readable %}
        <h2>Active {{ category_human_readable }} Listings</h2>
    {% else %}
        <h2>Active Listings</h2>
    {% endif %}
    
    {% for auction in auctions %}
        
        <div class="card">
            <div class="row g-0">
                <div class="col-4">
                    <img class="img-fluid rounded" src="{{ auction.image }}" alt="This auction has no image">
                </div>
                <div class="col-8">
                    <div class="card-body">
                        <h3 class="card-title">Title: <a href="{% url 'auction' auction.id %}">{{ auction.title }}</a></h3>
                        <p class="card-subtitle text-muted">Category: 
                            {% if auction.get_category_display %}
                                {{ auction.get_category_display }}
                            {% else %}
                                No category Listed
                            {% endif %}
                        </p>
                        <p class="card-text"><b>Price: ${{ auction.price }}</b></p>
                        <p class="card-text">Description: {{ auction.description }}</p>
                        <div class="card-footer"><span class="text-muted" style="font-size: small">Created: {{ auction.creationDate }}</span></div>
                    </div>
                </div>
            </div>
        </div>
        
    {% endfor %}
    
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class='container'>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">
                        Watchlist
                        <span class="badge bg-secondary text-white">{{ auctions_in_watchlist }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_auction' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
    <div>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}